Repository eggsy/website, pull requests merged in 2021-05, with the labels that each got.

#13 fix: show hidden repos
  src/pages/index.vue
Labels: enhancement

#14 fix: typo
  README.md
Labels: bug, documentation

#15 fix: Small typo in blog post
  src/content/slowly-yeni-koye-eski-adet.md
Labels: typo

#16 fix: some typos
  src/content/aur-discord-yukleme.md
  src/content/blog-yenilendi.md
  src/content/blogun-baslica-ozellikleri.md
  src/content/botlastirilmis-kullanici-hesaplari-neden-yasak.md
  src/content/discord-server-templates-yayinda.md
  src/content/discord-sunucum-yenilendi.md
  src/content/dizi-onerilerim.md
  src/content/erasmus-icin-pasaport-almak.md
  src/content/imgur-please-artik-unblock-please.md
  src/content/imgur-please-nedir.md
  src/content/is-inside-nasil-kullanilir.md
  src/content/manjaro-nedir.md
  src/content/nedir-bu-blog.md
  src/content/neler-donuyor.md
  src/content/octopi-aur-destegi-nasil-aktiflestirilir.md
  src/content/okul-gunlukleri-podcast.md
  src/content/okul-gunlukleri.md
  src/content/premid-nasil-kullanilir.md
  src/content/renk-degistiren-roller-neden-yasak.md
  src/content/site-artik-acik-kaynak.md
  src/content/slowly-yeni-koye-eski-adet.md
  src/content/sunucudaki-herkese-dm-atmak-neden-yasak.md
  src/content/vue-nuxt-nedir.md
  src/content/yeni-alan-adi.md
Labels: typo
